#!/bin/bash
# =============================================================================
# init-space.sh - 创建新的 AI-Driven workspace
#
# 用法:
#   bash .cursor/skills/ai-driven-management/scripts/init-space.sh <space_name> [code_root1] ...
#
# 示例:
#   bash scripts/init-space.sh my_space                              # 空 workspace
#   bash scripts/init-space.sh poker ../ai-projects/ios-poker-game   # 带代码目录
#   bash scripts/init-space.sh app "../frontend" "../backend"        # 多代码目录
#
# 环境变量（详见 common.sh）:
#   AI_ROOT            ai-driven 所在的父目录
#   AI_DRIVEN_ROOT     ai-driven 仓库根目录
#   WORKSPACES_PATH    自定义 workspaces 存放路径
# =============================================================================

set -e

# === 加载公共配置 ===
CALLER_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$CALLER_SCRIPT_DIR/common.sh"
_validate_ai_driven_root

# === 解析参数 ===
SPACE_NAME="$1"
shift || true
CODE_ROOTS=("$@")  # 可以为空

# === 验证 ===
if [ -z "$SPACE_NAME" ]; then
    echo "用法: $0 <space_name> [code_root1] [code_root2] ..."
    echo ""
    echo "示例:"
    echo "  $0 my_space                        # 空 workspace"
    echo "  $0 poker ../ai-projects/poker      # 带代码目录"
    exit 1
fi

if [[ ! "$SPACE_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "错误: workspace 名称只能包含字母、数字、下划线和连字符"
    exit 1
fi

SPACE_ROOT="$WORKSPACES_PATH/$SPACE_NAME"

if [ -d "$SPACE_ROOT" ]; then
    echo "错误: $SPACE_ROOT 已存在"
    exit 1
fi

if [ ! -d "$TEMPLATE_DIR" ]; then
    echo "错误: 未找到模板目录 $TEMPLATE_DIR"
    exit 1
fi

echo "创建 workspace: $SPACE_NAME"
info "AI_ROOT: $AI_ROOT"
info "AI_DRIVEN_ROOT: $AI_DRIVEN_ROOT"
[ ${#CODE_ROOTS[@]} -gt 0 ] && echo "  代码目录: ${CODE_ROOTS[*]}"
echo ""

# === 1. 从模板复制 ===
echo "从模板复制..."
mkdir -p "$SPACE_ROOT"
cp -r "$TEMPLATE_DIR"/. "$SPACE_ROOT/" 2>/dev/null || true
# 复制隐藏文件
for f in "$TEMPLATE_DIR"/.*; do
    [ -e "$f" ] || continue
    [ "$(basename "$f")" = "." ] || [ "$(basename "$f")" = ".." ] && continue
    cp -r "$f" "$SPACE_ROOT/" 2>/dev/null || true
done

# === 2. 生成 .space-config ===
echo "生成配置..."

CODE_ROOTS_ABS_LIST=()
for code_root in "${CODE_ROOTS[@]}"; do
    if [[ "$code_root" = /* ]]; then
        CODE_ROOT_ABS="$code_root"
    else
        CODE_ROOT_ABS="$(cd "$code_root" 2>/dev/null && pwd)" || CODE_ROOT_ABS=""
    fi
    # 如果目录不存在，创建
    if [ -z "$CODE_ROOT_ABS" ] || [ ! -d "$CODE_ROOT_ABS" ]; then
        FULL_PATH="$code_root"
        [[ "$FULL_PATH" != /* ]] && FULL_PATH="$(pwd)/$code_root"
        echo "  -> 创建代码目录: $FULL_PATH"
        mkdir -p "$FULL_PATH"
        CODE_ROOT_ABS="$(cd "$FULL_PATH" 2>/dev/null && pwd)" || true
    fi
    [ -n "$CODE_ROOT_ABS" ] && CODE_ROOTS_ABS_LIST+=("$CODE_ROOT_ABS")
done

CODE_ROOTS_ABS_STR="$(IFS=,; echo "${CODE_ROOTS_ABS_LIST[*]}")"

cat > "$SPACE_ROOT/.space-config" << EOF
# Workspace Configuration (generated by init-space.sh)
SPACE_NAME="$SPACE_NAME"
CODE_ROOTS="${CODE_ROOTS[*]}"
CODE_ROOTS_ABS="$CODE_ROOTS_ABS_STR"
EOF

# === 3. 生成 .code-workspace ===
echo "生成 .code-workspace..."

FOLDERS=("{\"path\": \".\"}")
for abs_path in "${CODE_ROOTS_ABS_LIST[@]}"; do
    FOLDERS+=("{\"path\": \"$abs_path\"}")
done
FOLDERS_JSON=$(IFS=,; echo "${FOLDERS[*]}")

cat > "$SPACE_ROOT/${SPACE_NAME}.code-workspace" << EOF
{
    "folders": [$FOLDERS_JSON],
    "settings": {}
}
EOF

# === 4. 初始化 OpenSpec 项目目录 ===
echo "初始化 OpenSpec 项目目录..."

# 检查全局 opsx 命令是否已安装
GLOBAL_OPSX_COUNT=$(ls "$CURSOR_HOME/commands"/opsx-*.md 2>/dev/null | wc -l | tr -d ' ')
if [ "$GLOBAL_OPSX_COUNT" -ge 8 ]; then
    echo "  全局 opsx 命令已就绪 ($GLOBAL_OPSX_COUNT 个)"
else
    echo "  警告: 全局 opsx 命令未安装或不完整 ($GLOBAL_OPSX_COUNT 个)"
    echo "  请先运行: bash $CALLER_SCRIPT_DIR/setup-global.sh"
fi

# 只创建 openspec/ 项目目录（变更记录用），不在 workspace 内生成 commands/skills
if command -v openspec &>/dev/null; then
    if (cd "$SPACE_ROOT" && openspec init --tools none 2>/dev/null); then
        echo "  OpenSpec 项目目录已创建"
    else
        echo "  警告: OpenSpec 初始化失败，手动创建目录"
        mkdir -p "$SPACE_ROOT/openspec/changes" "$SPACE_ROOT/openspec/specs"
    fi
else
    echo "  openspec 未安装，手动创建目录"
    mkdir -p "$SPACE_ROOT/openspec/changes" "$SPACE_ROOT/openspec/specs"
    echo "  安装 openspec: npm i -g @fission-ai/openspec@latest"
fi
# 容错：确保目录存在
mkdir -p "$SPACE_ROOT/.cursor/commands" "$SPACE_ROOT/.cursor/rules"

# === 5. 追加 .gitignore 规则 ===
for code_root in "${CODE_ROOTS[@]}"; do
    CODE_ROOT_ABS="$(cd "$code_root" 2>/dev/null && pwd)" || true
    if [ -n "$CODE_ROOT_ABS" ]; then
        CODE_ROOT_NAME="$(basename "$CODE_ROOT_ABS")"
        if ! grep -q "^$CODE_ROOT_NAME/" "$SPACE_ROOT/.gitignore" 2>/dev/null; then
            echo "$CODE_ROOT_NAME/" >> "$SPACE_ROOT/.gitignore"
        fi
    fi
done

# === 6. 生成 README.md ===
cat > "$SPACE_ROOT/README.md" << EOF
# $SPACE_NAME

AI 自主开发 workspace。

## 入口

\`\`\`
/team 做一个用户认证
\`\`\`

## 原则

- 人只说需求
- AI 全自动
- 中间不需要人确认
EOF

# === 7. git init ===
cd "$SPACE_ROOT"
git init -q
git add -A
git commit -q -m "初始化 $SPACE_NAME workspace" 2>/dev/null || true

echo ""
echo "=========================================="
echo "  创建完成: $SPACE_NAME"
echo "=========================================="
echo ""
echo "目录: $SPACE_ROOT/"
echo ""
echo "下一步:"
echo "  1. 打开: $SPACE_ROOT/${SPACE_NAME}.code-workspace"
echo "  2. 输入: /team 做一个 xxx"
