#!/bin/bash
# =============================================================================
# init-space.sh - 创建新的 AI-Driven workspace
#
# 用法:
#   bash .cursor/skills/ai-driven-management/scripts/init-space.sh <space_name> [code_root1] ...
#
# 示例:
#   bash scripts/init-space.sh my_space                              # 空 workspace
#   bash scripts/init-space.sh poker ../ai-projects/ios-poker-game   # 带代码目录
#   bash scripts/init-space.sh app "../frontend" "../backend"        # 多代码目录
#
# 环境变量:
#   WORKSPACES_PATH  自定义 workspaces 存放路径（默认: ai-driven/workspaces）
# =============================================================================

set -e

# === 可配置路径（环境变量 > 默认值）===
# scripts/ -> ai-driven-management/ -> skills/ -> .cursor/ -> ai-driven root
AI_DRIVEN_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
WORKSPACES_PATH="${WORKSPACES_PATH:-$AI_DRIVEN_ROOT/workspaces}"
TEMPLATE_DIR="$AI_DRIVEN_ROOT/common/workspace-template"

# === 解析参数 ===
SPACE_NAME="$1"
shift || true
CODE_ROOTS=("$@")  # 可以为空

# === 验证 ===
if [ -z "$SPACE_NAME" ]; then
    echo "用法: $0 <space_name> [code_root1] [code_root2] ..."
    echo ""
    echo "示例:"
    echo "  $0 my_space                        # 空 workspace"
    echo "  $0 poker ../ai-projects/poker      # 带代码目录"
    exit 1
fi

if [[ ! "$SPACE_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "错误: workspace 名称只能包含字母、数字、下划线和连字符"
    exit 1
fi

SPACE_ROOT="$WORKSPACES_PATH/$SPACE_NAME"

if [ -d "$SPACE_ROOT" ]; then
    echo "错误: $SPACE_ROOT 已存在"
    exit 1
fi

if [ ! -d "$TEMPLATE_DIR" ]; then
    echo "错误: 未找到模板目录 $TEMPLATE_DIR"
    exit 1
fi

echo "创建 workspace: $SPACE_NAME"
[ ${#CODE_ROOTS[@]} -gt 0 ] && echo "  代码目录: ${CODE_ROOTS[*]}"
echo ""

# === 1. 从模板复制 ===
echo "从模板复制..."
mkdir -p "$SPACE_ROOT"
cp -r "$TEMPLATE_DIR"/. "$SPACE_ROOT/" 2>/dev/null || true
# 复制隐藏文件
for f in "$TEMPLATE_DIR"/.*; do
    [ -e "$f" ] || continue
    [ "$(basename "$f")" = "." ] || [ "$(basename "$f")" = ".." ] && continue
    cp -r "$f" "$SPACE_ROOT/" 2>/dev/null || true
done

# === 2. 生成 .space-config ===
echo "生成配置..."

CODE_ROOTS_ABS_LIST=()
for code_root in "${CODE_ROOTS[@]}"; do
    if [[ "$code_root" = /* ]]; then
        CODE_ROOT_ABS="$code_root"
    else
        CODE_ROOT_ABS="$(cd "$code_root" 2>/dev/null && pwd)" || CODE_ROOT_ABS=""
    fi
    # 如果目录不存在，创建
    if [ -z "$CODE_ROOT_ABS" ] || [ ! -d "$CODE_ROOT_ABS" ]; then
        FULL_PATH="$code_root"
        [[ "$FULL_PATH" != /* ]] && FULL_PATH="$(pwd)/$code_root"
        echo "  -> 创建代码目录: $FULL_PATH"
        mkdir -p "$FULL_PATH"
        CODE_ROOT_ABS="$(cd "$FULL_PATH" 2>/dev/null && pwd)" || true
    fi
    [ -n "$CODE_ROOT_ABS" ] && CODE_ROOTS_ABS_LIST+=("$CODE_ROOT_ABS")
done

CODE_ROOTS_ABS_STR="$(IFS=,; echo "${CODE_ROOTS_ABS_LIST[*]}")"

cat > "$SPACE_ROOT/.space-config" << EOF
# Workspace Configuration (generated by init-space.sh)
SPACE_NAME="$SPACE_NAME"
CODE_ROOTS="${CODE_ROOTS[*]}"
CODE_ROOTS_ABS="$CODE_ROOTS_ABS_STR"
EOF

# === 3. 生成 .code-workspace ===
echo "生成 .code-workspace..."

FOLDERS=("{\"path\": \".\"}")
for abs_path in "${CODE_ROOTS_ABS_LIST[@]}"; do
    FOLDERS+=("{\"path\": \"$abs_path\"}")
done
FOLDERS_JSON=$(IFS=,; echo "${FOLDERS[*]}")

cat > "$SPACE_ROOT/${SPACE_NAME}.code-workspace" << EOF
{
    "folders": [$FOLDERS_JSON],
    "settings": {}
}
EOF

# === 4. 初始化 OpenSpec ===
echo "初始化 OpenSpec..."
if ! command -v openspec &>/dev/null; then
    echo "  openspec 未安装，尝试自动安装..."
    if npm i -g @fission-ai/openspec@latest 2>/dev/null; then
        echo "  openspec 已安装: $(openspec --version 2>/dev/null)"
    else
        echo "  警告: openspec 自动安装失败"
        echo "  手动安装: npm i -g @fission-ai/openspec@latest"
    fi
fi

if command -v openspec &>/dev/null; then
    if (cd "$SPACE_ROOT" && openspec init --tools cursor 2>/dev/null); then
        # 验证关键文件是否生成
        if [ -f "$SPACE_ROOT/.cursor/commands/opsx-new.md" ]; then
            OPSX_COUNT=$(ls "$SPACE_ROOT/.cursor/commands"/opsx-*.md 2>/dev/null | wc -l | tr -d ' ')
            echo "  OpenSpec 已初始化 ($OPSX_COUNT 个命令)"
        else
            echo "  警告: OpenSpec init 完成但未生成 opsx-*.md 命令文件"
            echo "  手动修复: cd $SPACE_ROOT && openspec init --tools cursor"
        fi
    else
        echo "  警告: OpenSpec 初始化失败"
        echo "  手动修复: cd $SPACE_ROOT && openspec init --tools cursor"
    fi
else
    echo "  警告: openspec 未安装，跳过"
    echo "  安装后修复: npm i -g @fission-ai/openspec@latest && cd $SPACE_ROOT && openspec init --tools cursor"
fi
# 容错：确保目录存在（即使 openspec init 失败）
mkdir -p "$SPACE_ROOT/.cursor/skills" "$SPACE_ROOT/.cursor/commands"

# === 5. 追加 .gitignore 规则 ===
for code_root in "${CODE_ROOTS[@]}"; do
    CODE_ROOT_ABS="$(cd "$code_root" 2>/dev/null && pwd)" || true
    if [ -n "$CODE_ROOT_ABS" ]; then
        CODE_ROOT_NAME="$(basename "$CODE_ROOT_ABS")"
        if ! grep -q "^$CODE_ROOT_NAME/" "$SPACE_ROOT/.gitignore" 2>/dev/null; then
            echo "$CODE_ROOT_NAME/" >> "$SPACE_ROOT/.gitignore"
        fi
    fi
done

# === 6. 生成 README.md ===
cat > "$SPACE_ROOT/README.md" << EOF
# $SPACE_NAME

AI 自主开发 workspace。

## 入口

\`\`\`
/team 做一个用户认证
\`\`\`

## 原则

- 人只说需求
- AI 全自动
- 中间不需要人确认
EOF

# === 7. git init ===
cd "$SPACE_ROOT"
git init -q
git add -A
git commit -q -m "初始化 $SPACE_NAME workspace" 2>/dev/null || true

echo ""
echo "=========================================="
echo "  创建完成: $SPACE_NAME"
echo "=========================================="
echo ""
echo "目录: $SPACE_ROOT/"
echo ""
echo "下一步:"
echo "  1. 打开: $SPACE_ROOT/${SPACE_NAME}.code-workspace"
echo "  2. 输入: /team 做一个 xxx"
